### ISSUE TITLE
Exporting in .cha not working

### ISSUE THREAD

**Issue by FraPet** [phon-ca/phontalk#10]
When I try to export the project in a .cha file, a warning is shown and the file it's not written. This is the error:

```
(Phon -> CHAT) …/test_analisi/xxx.xml -> …/TFFD_Phon2/test_analisi/xxx.cha
	WARNING: An illegal reflective access operation has occurred
	WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector (file:/Applications/Phon.app/Contents/Resources/app/bin/chatter.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
	WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector
	WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
	WARNING: All illegal access operations will be denied in a future release
	0*** File "chatter18213677038277292574.xml": line 583, column 13: tree parser: required (...)+ loop did not match anything at input ''
	0*** File "chatter18213677038277292574.xml": line 6379, column 13: tree parser: required (...)+ loop did not match anything at input ''
	*** org.talkbank.util.WalkerTalkBankException
		at org.talkbank.chatter.App.processTree(App.java:1036)
		at org.talkbank.chatter.App.processFile(App.java:955)
		at org.talkbank.chatter.App.<init>(App.java:400)
		at org.talkbank.chatter.App.<init>(App.java:207)
		at org.talkbank.chatter.App.main(App.java:176)
	Number of files failed: 1
	Output file not written
```
How can I solve this?

**Comment by ghedlund** [comment]
Hello, 

The conversion to CHAT occurs in 2 phases:
 1) Phon -> TalkBank XML (https://www.talkbank.org/)
 2) TalkBank XML -> CHAT (using an external application call Chatter available from the talkbank site)

It appears as though this error happens during the second phase of the conversion. Unfortunately I'm not able to provide much more information without the original source file. A beta update of Phon will be available over the next couple of days with updates which should make some of these data issues more easy to find. Once the beta is available you can use the [Check Sessions](https://www.phon.ca/phon-manual/project_manager/project_manager.html?hl=check%2Csessions) action to view issues related to CHAT/TalkBank export.
